### ISSUE TITLE
it doesn't seem like the bomb cells have any effect on the algorithm

### ISSUE THREAD

**Issue by ekleiman22** [naman114/Graph-Algorithm-Visualizer#3]
The path found goes through the bombs cells. So what does mean a bomb cell?

**Comment by naman114** [comment]
Hi @ekleiman22
 
**Just for context:**
The bomb cells are applicable to only the Dijkstra's algorithm and not the other algorithms.

Since Dijkstra's algorithm finds the shortest path between nodes in a weighted graph, we need the cells in the grid to have different _weights_ to visualise this. This is why I have given the option to convert cells to bomb cells. A bomb cell has a weight of 10 and a non-bomb cell has a weight of 1. 

**Coming to your question now:**
The algorithm will try to find the shortest path and while doing that, it will try to avoid the bomb cells to find the path with the least total weight. However, if there exists no path in which bomb cells can be avoided completely, it will have to go through the bomb cells.

**Comment by ekleiman22** [comment]
Thanks. Understand.
